# Generated by Django 3.1.4 on 2021-01-18 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('Name', models.CharField(max_length=64, verbose_name='Имя')),
                ('Patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('PassportSeries', models.IntegerField(blank=True, default=0, verbose_name='Серия паспорта')),
                ('PassportID', models.IntegerField(blank=True, default=0, verbose_name='Номер паспорта')),
                ('PhoneNumber', models.IntegerField(blank=True, default=0, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['Surname'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Surname', models.CharField(max_length=64)),
                ('Patronymic', models.CharField(max_length=64)),
                ('PhoneNumber', models.IntegerField(blank=True, default=0)),
                ('Age', models.IntegerField(blank=True, default=0)),
                ('Position', models.CharField(max_length=64)),
                ('Salary', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['Surname'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfRegistration', models.DateTimeField(auto_now=True)),
                ('DateOfCompletion', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(max_length=64)),
                ('ClientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.client')),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.employee')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['DateOfRegistration'],
            },
        ),
        migrations.CreateModel(
            name='Paddock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=64)),
                ('NumberOfPlaces', models.IntegerField(blank=True, default=0)),
                ('Area', models.FloatField(blank=True, default=0)),
                ('PriceOfRent', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Загон',
                'verbose_name_plural': 'Загоны',
                'ordering': ['Address'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Surname', models.CharField(max_length=64)),
                ('Patronymic', models.CharField(max_length=64)),
                ('Address', models.CharField(max_length=64)),
                ('PhoneNumber', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['Surname'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kind', models.CharField(max_length=32)),
                ('Price', models.FloatField(blank=True, default=0)),
                ('Count', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Cырье',
                'verbose_name_plural': 'Сырье',
                'ordering': ['Price'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вакцинация',
                'verbose_name_plural': 'Вакцинации',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=128)),
                ('Name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Diseade', models.CharField(max_length=64)),
                ('Validity', models.IntegerField(blank=True, default=0)),
                ('VaccinationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.vaccination')),
            ],
            options={
                'verbose_name': 'Вакцина',
                'verbose_name_plural': 'Вакцины',
                'ordering': ['Diseade'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfSupply', models.DateTimeField(auto_now=True)),
                ('Price', models.FloatField(blank=True, default=0)),
                ('Count', models.FloatField(blank=True, default=0)),
                ('Cost', models.FloatField(blank=True, default=0)),
                ('ProviderID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.provider')),
                ('RawMaterialID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.rawmaterial')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['Cost'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='WarehousId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.warehouse'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kind', models.CharField(max_length=32)),
                ('Price', models.FloatField(blank=True, default=0)),
                ('DateOfReceiving', models.DateTimeField(auto_now_add=True)),
                ('ShelfLife', models.IntegerField(blank=True, default=0)),
                ('Count', models.FloatField(blank=True, default=0)),
                ('WarehousId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.warehouse')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['Kind'],
            },
        ),
        migrations.CreateModel(
            name='Ostrich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=64)),
                ('Sex', models.CharField(max_length=64)),
                ('HealthStatus', models.CharField(max_length=64)),
                ('PaddockID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.paddock')),
                ('VaccinationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.vaccination')),
            ],
            options={
                'verbose_name': 'Страус',
                'verbose_name_plural': 'Страусы',
                'ordering': ['PaddockID'],
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField(blank=True, default=0)),
                ('Cost', models.FloatField(blank=True, default=0)),
                ('Count', models.FloatField(blank=True, default=0)),
                ('OrderID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.order')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.product')),
            ],
            options={
                'verbose_name': 'Заказ продукта',
                'verbose_name_plural': 'Заказы продуктов',
                'ordering': ['OrderID'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='WarehouseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.warehouse'),
        ),
    ]
