# Generated by Django 3.1.4 on 2021-01-19 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ferm', '0003_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ShelfLife',
        ),
        migrations.AddField(
            model_name='order',
            name='Cost',
            field=models.FloatField(default=0, verbose_name='Cтоимость'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Age',
            field=models.IntegerField(blank=True, default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Patronymic',
            field=models.CharField(max_length=64, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PhoneNumber',
            field=models.IntegerField(blank=True, default=0, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Position',
            field=models.CharField(max_length=64, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Salary',
            field=models.IntegerField(blank=True, default=0, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Surname',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='WarehouseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ClientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='DateOfCompletion',
            field=models.DateTimeField(blank=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='DateOfRegistration',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='EmployeeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ferm.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='Cost',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='Count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='OrderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='Price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='ProductID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='ostrich',
            name='HealthStatus',
            field=models.CharField(max_length=64, verbose_name='Статус здоровья'),
        ),
        migrations.AlterField(
            model_name='ostrich',
            name='Nickname',
            field=models.CharField(max_length=64, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='ostrich',
            name='PaddockID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.paddock', verbose_name='Загон'),
        ),
        migrations.AlterField(
            model_name='ostrich',
            name='Sex',
            field=models.CharField(max_length=64, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='ostrich',
            name='VaccinationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.vaccination', verbose_name='Вакцинация'),
        ),
        migrations.AlterField(
            model_name='paddock',
            name='Address',
            field=models.CharField(blank=True, max_length=64, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='paddock',
            name='Area',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='paddock',
            name='NumberOfPlaces',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='paddock',
            name='PriceOfRent',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена аренды'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='DateOfReceiving',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Kind',
            field=models.CharField(max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='WarehousId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferm.warehouse', verbose_name='Склад'),
        ),
    ]
