# Generated by Django 3.1.4 on 2021-01-19 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferm', '0004_auto_20210119_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DateOfCompletion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='DateOfRegistration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='EmployeeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferm.employee', verbose_name='Сотрудник'),
        ),
    ]
