# Generated by Django 3.1.4 on 2021-01-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferm', '0005_auto_20210119_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='Kind',
            field=models.CharField(default='Перья', max_length=32, verbose_name='Тип'),
        ),
    ]
